sudo: false
dist: xenial
services:
  - docker
language: python
python:
  - "3.6"
notifications:
  email: false
before_install:
- docker-compose build
- docker-compose up -d
- pip install --upgrade pip
script: python3 test.py
